import { StyleSheet, Dimensions } from 'react-native';
import { colors, typography } from '../../../styles/globalStyles';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    safe: {
        flex: 1,
    },
    tabBar: {
        flexDirection: 'row',
        backgroundColor: colors.white,
        borderBottomWidth: 1,
        borderBottomColor: colors.boderLight,
        height: height / 20,
    },
    tab: {
        height: height / 20,
        width: width / 2,
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
    },
    tabText: {
        fontSize: typography.size.sm,
        fontWeight: '500',
        color: colors.textMuted,
        fontFamily: typography.regular,
    },
    activeTabText: {
        color: colors.primary,
        fontWeight: '700',
        fontFamily: typography.bold,
    },
    tabUnderline: {
        position: 'absolute',
        bottom: 0,
        width: width / 2,
        borderBottomWidth: 2,
        borderColor: colors.primaryDark,
        borderRadius: 2,
    },
    scroll: {
        flex: 1,
    },
    sectionCon: {
        height: height / 17,
        width: width,
        justifyContent: 'center',
        alignItems: 'center',
    },
    sectionTitle: {
        fontSize: typography.size.sm,
        fontWeight: '700',
        color: colors.primary,
        fontFamily: typography.bold,
        textAlign: 'center',
        lineHeight: 18,
    },
    divider: {
        height: height / 80,
        backgroundColor: '#E8F0F8',
        marginTop: height / 40,
    },
    spaceCon: {
        height: height / 5.5,
        width: width,
        justifyContent: 'center',
        alignItems: 'center',
    },
    card: {
        height: height / 6.05,
        width: width / 1.1,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
        elevation: 2,
        backgroundColor: colors.white,
        alignSelf: 'center',
        borderRadius: 8,
        borderWidth: 0.5,
        borderColor: colors.accent,
    },
    titleCon: {
        height: height / 25,
        width: width / 1.2,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        alignSelf: 'center',
    },
    cardTitle: {
        fontSize: typography.size.md,
        fontWeight: '700',
        fontFamily: typography.bold,
        color: colors.text,
        flex: 1,
        paddingRight: width / 40,
    },
    creditBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: width / 60,
    },
    dot: {
        width: width / 40,
        height: width / 40,
        borderRadius: width / 80,
        backgroundColor: colors.primary,
    },
    creditText: {
        fontSize: typography.size.xs,
        color: colors.primary,
        fontWeight: '600',
        fontFamily: typography.semiBold,
    },
    cardMeta: {
        height: height / 12,
        width: width / 1.2,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        alignSelf: 'center',
    },
    cardTop: {
        height: height / 15,
        width: width / 1.5,
        justifyContent: 'space-evenly',
    },
    metaText: {
        fontSize: typography.size.xs,
        color: colors.textMuted,
        fontFamily: typography.regular,
    },
    locationText: {
        fontSize: typography.size.xs,
        color: colors.textMuted,
        fontFamily: typography.regular,
    },
    checkInRow: {
        backgroundColor: colors.lightBlue,
        borderBottomRightRadius: 8,
        borderBottomLeftRadius: 8,
        height: height / 25,
        width: width / 1.11,
        borderTopWidth: 0.5,
        borderColor: colors.primaryLight,
        alignSelf: 'center',
    },
    checkInCon: {
        height: height / 25,
        width: width / 1.2,
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'center',
    },
    checkInLabel: {
        fontSize: typography.size.xs,
        color: colors.textMuted,
        fontFamily: typography.regular,
    },
    checkInValue: {
        fontSize: typography.size.xs,
        fontWeight: '700',
        fontFamily: typography.bold,
        color: colors.text,
    },
    
    spaceBox: {
        width: width,
        height: height / 9.5,
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    teamCard: {
        backgroundColor: colors.white,
        borderRadius: 8,
        borderWidth: 0.5,
        borderColor: colors.border,
        width: width / 1.1,
        height: height / 11,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 2,
    },
    teamCardLeft: {
        width: width / 1.8,
        height: height / 12,
    },
    nameCon: {
        height: height / 25,
        width: width / 1.9,
        justifyContent: 'flex-end',
        alignSelf: 'flex-end',
    },
    teamName: {
        fontSize: typography.size.md,
        fontWeight: '700',
        fontFamily: typography.bold,
        color: colors.textDark,
    },
    teamCon: {
        height: height / 30,
        width: width / 1.9,
        justifyContent: 'center',
        alignSelf: 'flex-end',
    },
    teamMembers: {
        fontSize: typography.size.xs,
        color: colors.textMuted,
        fontFamily: typography.regular,
    },
    teamCardRight: {
        flexDirection: 'row',
        alignItems: 'center',
        width: width / 2.9,
        justifyContent: 'flex-end',
    },
    pointsBadge: {
        height: height / 35,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.lightBlue,
        borderRadius: 35,
        paddingHorizontal: 5,
        justifyContent: 'center',
    },
    pointsText: {
        fontSize: typography.size.xs,
        color: colors.primary,
        fontWeight: '500',
        fontFamily: typography.semiBold,
        paddingHorizontal: 3,
    },
    arrowCon: {
        height: height / 12,
        width: width / 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
});

export const tableStyles = StyleSheet.create({
    wrapper: {
        width: width / 1.08,
        alignSelf: 'center',
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 8,
        overflow: 'hidden',
        backgroundColor: colors.white,
    },
    row: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    lastRow: {
        borderBottomWidth: 0,
    },
    cell: {
        flex: 1,
        height: height / 20,
        justifyContent: 'center',
        alignItems: 'center',
        borderRightWidth: 1,
        borderRightColor: colors.border,
        paddingHorizontal: width / 80,
    },
    lastCell: {
        borderRightWidth: 0,
    },
    categoryCell: {
        flex: 1.8,
        alignItems: 'flex-start',
        paddingLeft: width / 30,
    },
    headerCell: {
        backgroundColor: colors.lightBlue,
        height: height / 20,
    },
    totalRowBg: {
        backgroundColor: colors.lightBlue,
    },
    headerText: {
        fontSize: typography.size.xs,
        fontFamily: typography.bold,
        fontWeight: '700',
        color: colors.textDark,
        textAlign: 'center',
    },
    categoryText: {
        fontSize: typography.size.xs,
        fontFamily: typography.regular,
        color: colors.textDark,
        textAlign: 'left',
    },
    valueText: {
        fontSize: typography.size.xs,
        fontFamily: typography.regular,
        color: colors.textDark,
        textAlign: 'center',
    },
    totalCategoryText: {
        fontSize: typography.size.xs,
        fontFamily: typography.bold,
        fontWeight: '700',
        color: colors.primary,
        textAlign: 'left',
    },
    totalValueText: {
        fontSize: typography.size.sm,
        fontFamily: typography.bold,
        fontWeight: '800',
        color: colors.primary,
        textAlign: 'center',
    },
});